=== BackupTheBerlios/beebb/Bee/program/web/config/config.dtd
<!-- glowny element sklada sie z sekcji -->
<!ELEMENT bee_configuration (general,database,behave,mailing,smiles)>
<!ATTLIST bee_configuration version CDATA #REQUIRED>

<!-- sekcja glowna -->
<!ELEMENT general (url_forum)>
<!ELEMENT url_forum (#PCDATA)>

<!-- sekcja bazy danych -->
<!ELEMENT database (host,user,password,database_name,tables_prefix,use_compres,use_ssl)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT database_name (#PCDATA)>
<!ELEMENT tables_prefix (#PCDATA)>
<!ELEMENT use_compres (#PCDATA)>
<!ELEMENT use_ssl (#PCDATA)>

<!-- sekcja zachowania sie forum -->
<!ELEMENT behave (guest_account,guest_id,log_in_max_age,minimum_pass_length,new_user_mail_auth,cache_counter)>
<!ELEMENT guest_account (#PCDATA)>
<!ELEMENT guest_id (#PCDATA)>
<!ELEMENT log_in_max_age (#PCDATA)>
<!ELEMENT minimum_pass_length (#PCDATA)>
<!ELEMENT new_user_mail_auth (#PCDATA)>
<!ELEMENT cache_counter (#PCDATA)>

<!-- sekcja konfiguracji poczty -->
<!ELEMENT mailing (smtp_server,mail_from,registration_subject,registration_body,forget_subject,forget_body)>
<!ELEMENT smtp_server (#PCDATA)>
<!ELEMENT mail_from (#PCDATA)>
<!ELEMENT registration_subject (#PCDATA)>
<!ELEMENT registration_body (#PCDATA)>
<!ELEMENT forget_subject (#PCDATA)>
<!ELEMENT forget_body (#PCDATA)>

<!ELEMENT smiles (smile_open_tag,smile_close_tag,(smile)*)>
<!ELEMENT smile_open_tag (#PCDATA)>
<!ELEMENT smile_close_tag (#PCDATA)>
<!ELEMENT smile (smile_tag,smile_url)>
<!ELEMENT smile_tag (#PCDATA)>
<!ELEMENT smile_url (#PCDATA)>

=== BackupTheBerlios/beebb/Bee/program/web/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bee_configuration SYSTEM "config.dtd">
<bee_configuration version="1.0">
<general>
<url_forum>http://127.0.0.1:8084/Bee</url_forum>
</general>
<database>
<host>localhost</host>
<user>bee</user>
<password>bee</password>
<database_name>Bee</database_name>
<tables_prefix>Bee</tables_prefix>
<use_compres>false</use_compres>
<use_ssl>false</use_ssl>
</database>

<behave>
<guest_account>Guest</guest_account>
<guest_id>1</guest_id>
<log_in_max_age>3600</log_in_max_age>
<minimum_pass_length>5</minimum_pass_length>
<new_user_mail_auth>true</new_user_mail_auth>
</behave>

<mailing>
<smtp_server>127.0.0.1</smtp_server>
<mail_from>bee@localhost</mail_from>
<registration_subject>[BEE] Rejestracja</registration_subject>
<registration_body>Właśnie założyłeś konto na forum Bee, poniżej znajduje się link w który należy kliknąć aby aktywować konto:</registration_body>
<forget_subject>[BEE] Zapomniane hasło</forget_subject>
<forget_body>Poniżej link do zmiany zapomnianego hasła:</forget_body>
</mailing>

<smiles>
<smile_open_tag>\:\|</smile_open_tag>
<smile_close_tag>\|\:</smile_close_tag>
<smile_tag>lol</smile_tag><smile_url>/Bee/images/smiles/default/lol.gif</smile_url>
<smile_tag>angel</smile_tag><smile_url>/Bee/images/smiles/default/angel.gif</smile_url>
<smile_tag>cry</smile_tag><smile_url>/Bee/images/smiles/default/cry.gif</smile_url>
<smile_tag>embarassed</smile_tag><smile_url>/Bee/images/smiles/default/embarassed.gif</smile_url>
<smile_tag>king</smile_tag><smile_url>/Bee/images/smiles/default/king.gif</smile_url>
<smile_tag>rotfl</smile_tag><smile_url>/Bee/images/smiles/default/rotfl.gif</smile_url>
<smile_tag>smile</smile_tag><smile_url>/Bee/images/smiles/default/smile.gif</smile_url>
<smile_tag>very_angry</smile_tag><smile_url>/Bee/images/smiles/default/very_angry.gif</smile_url>
<smile_tag>wow</smile_tag><smile_url>/Bee/images/smiles/default/wow.gif</smile_url>
<smile_tag>angry</smile_tag><smile_url>/Bee/images/smiles/default/angry.gif</smile_url>
<smile_tag>evil</smile_tag><smile_url>/Bee/images/smiles/default/evil.gif</smile_url>
<smile_tag>sad</smile_tag><smile_url>/Bee/images/smiles/default/sad.gif</smile_url>
<smile_tag>student</smile_tag><smile_url>/Bee/images/smiles/default/student.gif</smile_url>
<smile_tag>very_happy</smile_tag><smile_url>/Bee/images/smiles/default/very_happy.gif</smile_url>
<smile_tag>beer</smile_tag><smile_url>/Bee/images/smiles/default/beer.gif</smile_url>
<smile_tag>dj</smile_tag><smile_url>/Bee/images/smiles/default/dj.gif</smile_url>
<smile_tag>give_up</smile_tag><smile_url>/Bee/images/smiles/default/give_up.gif</smile_url>
<smile_tag>ok</smile_tag><smile_url>/Bee/images/smiles/default/ok.gif</smile_url>
<smile_tag>tongue</smile_tag><smile_url>/Bee/images/smiles/default/tongue.gif</smile_url>
<smile_tag>wink</smile_tag><smile_url>/Bee/images/smiles/default/wink.gif</smile_url>

<smile_tag>afraid</smile_tag><smile_url>/Bee/images/smiles/default/afraid.gif</smile_url>
<smile_tag>afro</smile_tag><smile_url>/Bee/images/smiles/default/afro.gif</smile_url>
<smile_tag>bag</smile_tag><smile_url>/Bee/images/smiles/default/bag.gif</smile_url>
<smile_tag>ban</smile_tag><smile_url>/Bee/images/smiles/default/ban.gif</smile_url>
<smile_tag>batman</smile_tag><smile_url>/Bee/images/smiles/default/batman.gif</smile_url>
<smile_tag>beksa</smile_tag><smile_url>/Bee/images/smiles/default/beksa.gif</smile_url>
<smile_tag>cenzura</smile_tag><smile_url>/Bee/images/smiles/default/cenzura.gif</smile_url>
<smile_tag>clever</smile_tag><smile_url>/Bee/images/smiles/default/clever.gif</smile_url>
<smile_tag>crooked</smile_tag><smile_url>/Bee/images/smiles/default/crooked.gif</smile_url>
<smile_tag>czat</smile_tag><smile_url>/Bee/images/smiles/default/czat.gif</smile_url>
<smile_tag>dead</smile_tag><smile_url>/Bee/images/smiles/default/dead.gif</smile_url>
<smile_tag>doctor</smile_tag><smile_url>/Bee/images/smiles/default/doctor.gif</smile_url>
<smile_tag>dots</smile_tag><smile_url>/Bee/images/smiles/default/dots.gif</smile_url>
<smile_tag>foxy</smile_tag><smile_url>/Bee/images/smiles/default/foxy.gif</smile_url>
<smile_tag>guns</smile_tag><smile_url>/Bee/images/smiles/default/guns.gif</smile_url>
<smile_tag>heart</smile_tag><smile_url>/Bee/images/smiles/default/heart.gif</smile_url>
<smile_tag>kid</smile_tag><smile_url>/Bee/images/smiles/default/kid.gif</smile_url>
<smile_tag>love</smile_tag><smile_url>/Bee/images/smiles/default/love.gif</smile_url>
<smile_tag>love2</smile_tag><smile_url>/Bee/images/smiles/default/love2.gif</smile_url>
<smile_tag>off_topic</smile_tag><smile_url>/Bee/images/smiles/default/off_topic.gif</smile_url>
<smile_tag>quite</smile_tag><smile_url>/Bee/images/smiles/default/quite.gif</smile_url>
<smile_tag>rip</smile_tag><smile_url>/Bee/images/smiles/default/rip.gif</smile_url>
<smile_tag>sleep</smile_tag><smile_url>/Bee/images/smiles/default/sleep.gif</smile_url>
<smile_tag>smoke</smile_tag><smile_url>/Bee/images/smiles/default/smoke.gif</smile_url>
<smile_tag>sour</smile_tag><smile_url>/Bee/images/smiles/default/sour.gif</smile_url>
<smile_tag>spam</smile_tag><smile_url>/Bee/images/smiles/default/spam.gif</smile_url>
<smile_tag>spue</smile_tag><smile_url>/Bee/images/smiles/default/spue.gif</smile_url>
<smile_tag>suck</smile_tag><smile_url>/Bee/images/smiles/default/suck.gif</smile_url>
<smile_tag>time</smile_tag><smile_url>/Bee/images/smiles/default/time.gif</smile_url>
<smile_tag>tv</smile_tag><smile_url>/Bee/images/smiles/default/tv.gif</smile_url>
<smile_tag>walkman</smile_tag><smile_url>/Bee/images/smiles/default/walkman.gif</smile_url>
<smile_tag>wc</smile_tag><smile_url>/Bee/images/smiles/default/wc.gif</smile_url>
<smile_tag>whistle</smile_tag><smile_url>/Bee/images/smiles/default/whistle.gif</smile_url>
</smiles>
</bee_configuration>
